apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-server
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
      - image: paleontolog/dev_ops:105
        name: hello-world
        ports:
          - containerPort: 8989
        readinessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 40
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 40
          periodSeconds: 15